version: '3.8'

services:
  postgres-sensors:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: sensors_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5452:5432"
    volumes:
      - pgdata-sensors:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d sensors_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-stats:
    image: postgres:16
    container_name: postgres_stats
    environment:
      POSTGRES_DB: stats_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5462:5432"
    volumes:
      - pgdata-stats:/var/lib/postgresql/data

  monitor-sensors:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monitor-sensors
    ports:
      - "8080:8080"
    depends_on:
      - postgres-sensors
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-sensors:5452/sensors_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_LIQUIBASE_ENABLED: "true"
    restart: on-failure

  statistics-service:
    build: ./statistics-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres-stats
      - monitor-sensors

volumes:
  pgdata-sensors:
  pgdata-stats:
