spring:
  datasource:
    url: jdbc:postgresql://localhost:5462/stats_db
    username: admin
    password: secret
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  application:
    name: statistics-service

server:
  port: 8081